%describe the background necessary to understand the lab's content, with some reservation (i.e., not too much detail)
%possibly provide walkthrough for simple problem
\section{Introduction}

In this lab, students will be provided with a “buggy” text encryption application for android to reinforce the concept of exception and error handling techniques. This application will contain a text box in which the students can enter a text string.  After pressing the “Encrypt” button, the text will be show in another box as an encrypted string. By pressing the “Decrypt” button, students will be presented with their original text. The students will have to debug this code and decide where to place try/catch statements in order for the application to work correctly.This lab will demonstrate the importance of error checking/handling in complex code.

An exception is an event, that occurs at the time of the execution of a program, which breaks the normal flow of the program's instructions. A program can use exceptions to point out that an error has taken place. To throw an exception, use the throw statement and provide it with an exception object (a descendant of Throwable) to give information about the specific error that occurred. A throws clause must be included in the decleration of method if a method throws an uncaught, checked exception. A program can catch exceptions by utilizing a combination of the try, catch, and finally blocks. The try block recognizes a block of code in which an exception can occur. The catch block determines a block of code, known as an exception handler, which can manage a particular kind of exception. The finally block identifies a block of code that will certainly execute, and is the appropriate place to close files, recover resources, and otherwise clean up after the code confined in the try block. The try statement must have at least one catch block or a finally block and can have multiple catch blocks. The type of exception thrown can be determined by the class of the exception object. More information about the error can be found by the exception object. With exception chaining, an exception can direct to the exception that caused it, which can successively detail about the exception that caused it, and so forth.
